{% set version = "4.4.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-smooth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/smooth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/smooth/smooth_{{ version }}.tar.gz
  sha256: 872e24e0ad125c1f42b0347eb36edd0d708d2dda642f75e5840135ba2cb8f497

build:
  number: 0
  missing_dso_whitelist:
    - $RPATH/R.dll                       # [win]
    - Library/bin/libgcc_s_seh-1.dll     # [win]
    - Library/bin/libstdc++-6.dll        # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-greybox >=2.0.2
    - r-rcpp >=0.12.3
    - r-rcpparmadillo >=0.8.100.0.0
    - r-generics >=0.1.2
    - r-pracma
    - r-statmod
    - r-mass
    - r-nloptr
    - r-xtable
    - r-zoo
    - libblas
    - libcblas
    - liblapack
  run:
    - r-base
    - r-greybox >=2.0.2
    - r-rcpp >=0.12.3
    - r-rcpparmadillo >=0.8.100.0.0
    - r-generics >=0.1.2
    - r-pracma
    - r-statmod
    - r-mass
    - r-nloptr
    - r-xtable
    - r-zoo

test:
  commands:
    - $R -e "library('smooth')"           # [not win]
    - "\"%R%\" -e \"library('smooth')\""   # [win]

about:
  home: https://github.com/config-i1/smooth
  license: LGPL-2.1-only
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1
  summary: Forecasting Using State Space Models
  description: |
    Functions implementing Single Source of Error state space models for
    purposes of time series analysis and forecasting. The package includes
    ADAM, Exponential Smoothing, SARIMA, Complex Exponential Smoothing,
    Simple Moving Average, and several simulation functions.
  dev_url: https://github.com/config-i1/smooth

extra:
  recipe-maintainers:
    - config-i1
