name: 🐛 Bug Report for R
description: Report a bug in the smooth package for R
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce the issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducible Example
      description: |
        Please provide a minimal, self-contained snippet of R code.
        Use synthetic data (e.g., `rnrom`) or a time series
        from the `datasets` or `Mcomp` package if necessary.
      render: R
      placeholder: |
        # Your code here...
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: Data Frequency
      description: What is the frequency of your time series?
      options:
        - Hourly/Minutely
        - Daily
        - Weekly
        - Monthly
        - Yearly
        - Irregular
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Info
      description: |
                   Run this and insert the output:
                   ```r
                   sessionInfo()
                   packageVersion("smooth")
                   ```
      placeholder: |
        - OS: macOS/Windows/Linux
        - R version: 4.5.1
        - Package version: 4.4.0
- type: checkboxes
  id: ai_usage
  attributes:
    label: Are you a robot?
    description: Was this issue (or the code behind it) created with AI assistance?
    options:
      - label: "Yes"
  validations:
    required: true
