"""
Comparison tests: CES Python vs R ces() / auto.ces() reference outputs.

Reference outputs were generated by:
  Rscript "tests/R scripts/ces_reference.R"

Each test case checks that Python's CES produces identical results to R:
  - Complex smoothing parameters (a, b)
  - Fitted values, residuals, forecasts
  - logLik, IC values (AIC, AICc, BIC, BICc)
  - Scale, persistence, states
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from smooth import CES, AutoCES
from smooth.adam_general import _adamCore
from smooth.adam_general.core.ces.cost_function import ces_cf
from smooth.adam_general.core.ces.creator import ces_creator

pytestmark = pytest.mark.r_parity

# ---------------------------------------------------------------------------
# Load reference data
# ---------------------------------------------------------------------------

_DATA_DIR = Path(__file__).parent / "data"
_REF_FILE = _DATA_DIR / "ces_reference.json"

with _REF_FILE.open() as _f:
    _REF = json.load(_f)


def _load_case(case_name):
    """Return (y, ref_dict) for the given case."""
    ref = _REF[case_name]
    df = pd.read_csv(_DATA_DIR / ref["data_file"])
    y = df["y"].values
    return y, ref


# ---------------------------------------------------------------------------
# Tolerances
# ---------------------------------------------------------------------------
# Rounding-level tolerances for deterministic R fixture parity.  These are
# the *default* class attributes on :class:`CESCaseTests` so individual
# test classes can override them when the case sits at the optimiser-
# convergence floor (Python's ``nlopt`` 2.10.0 and R's ``nloptr`` 2.2.1
# both wrap the same NLopt 2.10.0 source, but are separately compiled
# binaries; their BOBYQA internal linear-system solve can produce a 1-ULP
# drift in the interpolation-set trial point, which cascades to a small
# end-to-end gap on flat-loss quarterly CES configurations — see
# ``TestCESPartialQuarterly`` for details).
ATOL_TIGHT = 1e-9
RTOL_TIGHT = 0.0
ATOL_FITTED = 1e-9
RTOL_FITTED = 0.0
ATOL_PARAM = 1e-9
RTOL_PARAM = 0.0
ATOL_IC = 1e-9


# ---------------------------------------------------------------------------
# Helper to fit a CES model from reference params
# ---------------------------------------------------------------------------
def _fit_ces(y, ref):
    """Fit a CES model using params from reference."""
    params = ref["python_params"]
    m = CES(
        seasonality=params["seasonality"],
        h=params["h"],
        holdout=params["holdout"],
        lags=params.get("lags"),
        initial=params.get("initial", "backcasting"),
    )
    m.fit(y)
    return m


def _ces_cf_from_reference(case_name):
    y, ref = _load_case(case_name)
    params = ref["python_params"]
    h = params["h"]
    obs_in_sample = len(y) - h if params["holdout"] and h > 0 else len(y)
    y_in_sample = y[:obs_in_sample]
    seasonality = params["seasonality"]
    lags = [int(lag) for lag in params.get("lags", [1])]
    y_frequency = max(lags)
    lags_model_seasonal = [lag for lag in lags if lag > 1] if y_frequency > 1 else lags
    if not lags_model_seasonal:
        lags_model_seasonal = lags
    n_seasonal = len(lags_model_seasonal)

    if seasonality == "none":
        components_number = 2
        lags_model_all = [1, 1]
    elif seasonality == "simple":
        components_number = 2 * n_seasonal
        lags_model_all = [lag for lag in lags_model_seasonal for _ in range(2)]
    elif seasonality == "partial":
        components_number = 2 + n_seasonal
        lags_model_all = [1, 1, *lags_model_seasonal]
    else:
        components_number = 2 + 2 * n_seasonal
        lags_model_all = [1, 1, *[lag for lag in lags_model_seasonal for _ in range(2)]]

    lags_model_max = max(lags_model_all)
    created = ces_creator(
        seasonality=seasonality,
        n_seasonal=n_seasonal,
        lags_model_seasonal=lags_model_seasonal,
        lags_model_all=lags_model_all,
        lags_model_max=lags_model_max,
        components_number=components_number,
        xreg_number=0,
        obs_in_sample=obs_in_sample,
        obs_states=obs_in_sample + lags_model_max,
        obs_all=len(y),
        y_in_sample=y_in_sample,
        y_frequency=y_frequency,
        lags=lags,
    )

    adam_cpp = _adamCore.adamCore(
        lags=np.array(lags_model_all, dtype=np.uint64),
        E="A",
        T="N",
        S="N",
        nNonSeasonal=0,
        nSeasonal=0,
        nETS=0,
        nArima=components_number,
        nXreg=0,
        nComponents=len(lags_model_all),
        constant=False,
        adamETS=False,
    )

    b_estimate = seasonality in ("partial", "full")
    return ces_cf(
        B=np.array(ref["B"], dtype=np.float64),
        mat_vt=created["mat_vt"],
        mat_wt=created["mat_wt"],
        mat_f=created["mat_f"],
        vec_g=created["vec_g"],
        a={"value": None, "estimate": True},
        b={
            "value": None,
            "estimate": b_estimate,
            "number": (
                1 if seasonality == "partial" else 2 if seasonality == "full" else 0
            ),
        },
        seasonality=seasonality,
        n_seasonal=n_seasonal,
        lags_model_seasonal=lags_model_seasonal,
        lags_model_max=lags_model_max,
        initial_type=params.get("initial", "backcasting"),
        xreg_model=False,
        xreg_number=0,
        initial_xreg_estimate=False,
        components_number=components_number,
        lags_model_all=lags_model_all,
        index_lookup_table=created["index_lookup_table"],
        profiles_recent_table=created["profiles_recent_table"],
        y_in_sample=y_in_sample,
        ot=np.ones(obs_in_sample, dtype=np.float64),
        ot_logical=np.ones(obs_in_sample, dtype=bool),
        obs_in_sample=obs_in_sample,
        n_iterations=(
            2
            if params.get("initial", "backcasting") in ("backcasting", "complete")
            else 1
        ),
        bounds="admissible",
        loss="likelihood",
        h=h,
        multisteps=False,
        adam_cpp=adam_cpp,
    )


# ---------------------------------------------------------------------------
# Generic test runner for a CES case
# ---------------------------------------------------------------------------
class CESCaseTests:
    """Mixin that implements all comparison tests for a single CES case."""

    case_name: str

    # Class-level tolerances — subclasses override for cases sitting at the
    # optimiser-convergence floor (e.g. TestCESPartialQuarterly).
    atol_tight: float = ATOL_TIGHT
    rtol_tight: float = RTOL_TIGHT
    atol_fitted: float = ATOL_FITTED
    rtol_fitted: float = RTOL_FITTED
    atol_param: float = ATOL_PARAM
    rtol_param: float = RTOL_PARAM
    atol_ic: float = ATOL_IC

    @pytest.fixture(autouse=True)
    def setup_model(self):
        self.y, self.ref = _load_case(self.case_name)
        self.m = _fit_ces(self.y, self.ref)

    def test_model_name(self):
        assert self.m.model_name == self.ref["model_name"]

    def test_a_real(self):
        assert np.isclose(
            self.m.a_.real,
            self.ref["a_real"],
            atol=self.atol_param,
            rtol=self.rtol_param,
        ), f"a.real: {self.m.a_.real} vs R {self.ref['a_real']}"

    def test_a_imag(self):
        assert np.isclose(
            self.m.a_.imag,
            self.ref["a_imag"],
            atol=self.atol_param,
            rtol=self.rtol_param,
        ), f"a.imag: {self.m.a_.imag} vs R {self.ref['a_imag']}"

    def test_loglik(self):
        assert np.isclose(
            self.m.loglik,
            self.ref["logLik"],
            atol=self.atol_ic,
            rtol=self.rtol_tight,
        ), f"logLik: {self.m.loglik} vs R {self.ref['logLik']}"

    def test_loss_value(self):
        assert np.isclose(
            self.m.loss_value,
            self.ref["loss_value"],
            atol=self.atol_ic,
            rtol=self.rtol_tight,
        ), f"loss: {self.m.loss_value} vs R {self.ref['loss_value']}"

    def test_aic(self):
        assert abs(self.m.aic - self.ref["aic"]) < self.atol_ic, (
            f"AIC: {self.m.aic} vs R {self.ref['aic']}"
        )

    def test_aicc(self):
        assert abs(self.m.aicc - self.ref["aicc"]) < self.atol_ic, (
            f"AICc: {self.m.aicc} vs R {self.ref['aicc']}"
        )

    def test_bic(self):
        assert abs(self.m.bic - self.ref["bic"]) < self.atol_ic, (
            f"BIC: {self.m.bic} vs R {self.ref['bic']}"
        )

    def test_bicc(self):
        assert abs(self.m.bicc - self.ref["bicc"]) < self.atol_ic, (
            f"BICc: {self.m.bicc} vs R {self.ref['bicc']}"
        )

    def test_scale(self):
        assert np.isclose(
            self.m.scale_,
            self.ref["scale"],
            atol=self.atol_param,
            rtol=self.rtol_param,
        ), f"scale: {self.m.scale_} vs R {self.ref['scale']}"

    def test_b_vector(self):
        r_B = np.array(self.ref["B"])
        p_B = np.array(self.m.coef)
        assert np.allclose(p_B, r_B, atol=self.atol_param, rtol=self.rtol_param), (
            f"B: {p_B} vs R {r_B}"
        )

    def test_persistence(self):
        r_pers = np.array(self.ref["persistence"])
        p_pers = np.array(self.m.persistence_vector)
        assert np.allclose(
            p_pers, r_pers, atol=self.atol_param, rtol=self.rtol_param
        ), f"persistence: {p_pers} vs R {r_pers}"

    def test_fitted_values(self):
        r_fitted = np.array(self.ref["fitted"])
        p_fitted = np.array(self.m.fitted)
        assert np.allclose(
            p_fitted, r_fitted, atol=self.atol_fitted, rtol=self.rtol_fitted
        ), f"Max fitted diff: {np.max(np.abs(p_fitted - r_fitted))}"

    def test_residuals(self):
        r_resid = np.array(self.ref["residuals"])
        p_resid = np.array(self.m.residuals)
        assert np.allclose(
            p_resid, r_resid, atol=self.atol_fitted, rtol=self.rtol_fitted
        ), f"Max residual diff: {np.max(np.abs(p_resid - r_resid))}"

    def test_forecast(self):
        h = self.ref["python_params"]["h"]
        fc = self.m.predict(h=h)
        p_fc = fc.mean.values
        r_fc = np.array(self.ref["forecast"])
        assert np.allclose(p_fc, r_fc, atol=self.atol_fitted, rtol=self.rtol_fitted), (
            f"Max forecast diff: {np.max(np.abs(p_fc - r_fc))}"
        )

    def test_states_shape(self):
        r_nrow = self.ref["states_nrow"]
        r_ncol = self.ref["states_ncol"]
        p_states = self.m.states
        assert p_states.shape == (r_nrow, r_ncol), (
            f"States shape: {p_states.shape} vs R ({r_nrow}, {r_ncol})"
        )

    def test_states_first_row(self):
        r_first = np.array(self.ref["states_first_row"])
        p_first = self.m.states[0, :]
        assert np.allclose(
            p_first, r_first, atol=self.atol_fitted, rtol=self.rtol_fitted
        ), f"States first row: {p_first} vs R {r_first}"

    def test_states_last_row(self):
        r_last = np.array(self.ref["states_last_row"])
        p_last = self.m.states[-1, :]
        assert np.allclose(
            p_last, r_last, atol=self.atol_fitted, rtol=self.rtol_fitted
        ), f"States last row: {p_last} vs R {r_last}"


# ---------------------------------------------------------------------------
# Concrete test classes (one per case in the JSON)
# ---------------------------------------------------------------------------


class TestCESNoneAirPassengers(CESCaseTests):
    case_name = "none_airpassengers"


class TestCESSimpleAirPassengers(CESCaseTests):
    case_name = "simple_airpassengers"


class TestCESPartialAirPassengers(CESCaseTests):
    case_name = "partial_airpassengers"


class TestCESFullAirPassengers(CESCaseTests):
    case_name = "full_airpassengers"


class TestCESNoneNonseasonal(CESCaseTests):
    case_name = "none_nonseasonal"


class TestCESNoneQuarterly(CESCaseTests):
    case_name = "none_quarterly"


class TestCESSimpleQuarterly(CESCaseTests):
    case_name = "simple_quarterly"


class TestCESPartialQuarterly(CESCaseTests):
    case_name = "partial_quarterly"
    # Optimiser-convergence floor: Python's nlopt 2.10.0 and R's nloptr 2.2.1
    # both wrap NLopt 2.10.0 but are separately compiled binaries.  At iter 7
    # of BOBYQA on this case the two binaries diverge by 1 ULP in B[0]
    # (Py 1.3722222222222222 vs R 1.372222222222222, hex `4a` vs `49`) — the
    # trial-point computation involves a small linear-system solve over the
    # interpolation set whose result is 1 ULP off between the two builds.
    # The trajectory then drifts to a ~2.7e-5 logLik gap; up to ~5.3e-3
    # absolute and ~1.1e-4 relative differences in fitted / residuals;
    # ~3.3e-4 in B / a_real / scale.  Tolerances are set with headroom over
    # the observed envelope.
    atol_ic = 1e-3  # logLik / loss / AIC / AICc / BIC / BICc
    atol_param = 5e-3  # a_real / a_imag / scale / B / persistence
    rtol_param = 1e-2
    atol_fitted = 1e-2  # fitted / residuals / forecast / states rows
    rtol_fitted = 1e-3


class TestCESFullQuarterly(CESCaseTests):
    case_name = "full_quarterly"


class TestCESPartialOptimalAirPassengers(CESCaseTests):
    case_name = "partial_optimal_airpassengers"


@pytest.mark.parametrize(
    "case_name",
    [
        "none_airpassengers",
        "simple_airpassengers",
        "partial_airpassengers",
        "full_airpassengers",
        "none_nonseasonal",
        "none_quarterly",
        "simple_quarterly",
        "partial_quarterly",
        "full_quarterly",
        "partial_optimal_airpassengers",
    ],
)
def test_ces_cost_function_matches_r_reference(case_name):
    ref = _REF[case_name]
    assert np.isclose(
        _ces_cf_from_reference(case_name),
        ref["loss_value"],
        atol=1e-9,
        rtol=0,
    )


# ---------------------------------------------------------------------------
# AutoCES tests
# ---------------------------------------------------------------------------


class TestAutoCESAirPassengers:
    """AutoCES on AirPassengers should select the same seasonality as R."""

    @pytest.fixture(autouse=True)
    def setup_model(self):
        self.y, self.ref = _load_case("auto_airpassengers")
        params = self.ref["python_params"]
        self.m = AutoCES(
            h=params["h"],
            holdout=params["holdout"],
            lags=params.get("lags"),
        )
        self.m.fit(self.y)

    def test_selected_seasonality(self):
        assert self.m.best_model_.seasonality == self.ref["selected_seasonality"], (
            "Selected:"
            f" {self.m.best_model_.seasonality} vs R"
            f" {self.ref['selected_seasonality']}"
        )

    def test_model_name(self):
        assert self.m.model_name == self.ref["model_name"]

    def test_loglik(self):
        assert np.isclose(
            self.m.best_model_.loglik, self.ref["logLik"], atol=ATOL_IC, rtol=RTOL_TIGHT
        )

    def test_aicc(self):
        assert abs(self.m.best_model_.aicc - self.ref["aicc"]) < ATOL_IC

    def test_forecast(self):
        h = self.ref["python_params"]["h"]
        fc = self.m.predict(h=h)
        p_fc = fc.mean.values
        r_fc = np.array(self.ref["forecast"])
        assert np.allclose(p_fc, r_fc, atol=ATOL_FITTED, rtol=RTOL_FITTED), (
            f"Max forecast diff: {np.max(np.abs(p_fc - r_fc))}"
        )


class TestAutoCESQuarterly:
    """AutoCES on quarterly data should select the same seasonality as R."""

    # AutoCES on quarterly data ends up at the same partial-CES optimum as
    # ``TestCESPartialQuarterly`` (R reports `selected_seasonality: partial`),
    # so it carries the same BOBYQA optimiser-floor tolerances — see the
    # ``TestCESPartialQuarterly`` comment for the 1-ULP-in-B[0] root cause.
    atol_ic = 1e-3
    atol_fitted = 1e-2
    rtol_fitted = 1e-3

    @pytest.fixture(autouse=True)
    def setup_model(self):
        self.y, self.ref = _load_case("auto_quarterly")
        params = self.ref["python_params"]
        self.m = AutoCES(
            h=params["h"],
            holdout=params["holdout"],
            lags=params.get("lags"),
        )
        self.m.fit(self.y)

    def test_selected_seasonality(self):
        assert self.m.best_model_.seasonality == self.ref["selected_seasonality"]

    def test_loglik(self):
        assert np.isclose(
            self.m.best_model_.loglik,
            self.ref["logLik"],
            atol=self.atol_ic,
            rtol=RTOL_TIGHT,
        )

    def test_forecast(self):
        h = self.ref["python_params"]["h"]
        fc = self.m.predict(h=h)
        p_fc = fc.mean.values
        r_fc = np.array(self.ref["forecast"])
        assert np.allclose(p_fc, r_fc, atol=self.atol_fitted, rtol=self.rtol_fitted)
