"""Parity tests of Python ADAM vcov/confint/summary against R's ``smooth::adam``.

Reference data is generated by ``python/tests/R scripts/generate_summary_reference.R``
into ``python/tests/data/summary/<scenario>/``:

* ``series.csv``  — the input series (so Python uses identical data)
* ``coef.csv``    — R's estimated coefficients (name, value)
* ``vcov.csv``    — R's ``vcov(m)`` covariance matrix
* ``confint.csv`` — R's ``confint(m, level=0.95)`` (S.E. + bounds, with row names)

Scenarios exercise every CI-clamping path: ``ANN``/``AAN`` (usual ETS),
``AAdN`` with ``bounds="admissible"`` (eigen-bounds + phi), and an ARIMA(1,0,1)
(AR/MA stationarity/invertibility clamping).

Coefficient-interval bounds match R tightly; standard errors of large-magnitude
initial states (``level``, ``ARIMAState*``) carry a few-percent finite-difference
Hessian noise, so those columns use a looser relative tolerance — matching the
repo's existing R-parity convention for optimiser-sensitive quantities.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from smooth.adam_general.core.adam import ADAM
from smooth.adam_general.core.utils.var_covar import (
    fisher_information,
    invert_fisher_information,
)

pytestmark = pytest.mark.r_comparison

DATA_DIR = Path(__file__).parent / "data" / "summary"

# Scenario -> ADAM(**kwargs)
SCENARIOS = {
    "ann": dict(model="ANN"),
    "aan": dict(model="AAN"),
    "aadn": dict(model="AAdN", bounds="admissible"),
    "arima": dict(model="NNN", ar_order=1, i_order=0, ma_order=1),
}


def _fit(scenario):
    kw = SCENARIOS[scenario]
    y = pd.read_csv(DATA_DIR / scenario / "series.csv")["value"].to_numpy()
    m = ADAM(lags=[1], initial="optimal", fi=True, **kw).fit(y)
    return m


def _r_coef(scenario):
    return pd.read_csv(DATA_DIR / scenario / "coef.csv")


@pytest.mark.parametrize("scenario", list(SCENARIOS))
def test_coef_names_match_r(scenario):
    m = _fit(scenario)
    assert m.coef_names == list(_r_coef(scenario)["name"])


@pytest.mark.parametrize("scenario", list(SCENARIOS))
def test_vcov_matches_r_at_same_b(scenario):
    """Decisive: invert the FI computed at R's coefficients, compare to R vcov."""
    m = _fit(scenario)
    r_B = _r_coef(scenario)["value"].to_numpy()
    r_vcov = pd.read_csv(DATA_DIR / scenario / "vcov.csv").to_numpy()

    FI = fisher_information(
        r_B,
        m._model_type,
        m._components,
        m._lags_model,
        m._adam_created,
        m._persistence,
        m._initials,
        m._arima,
        m._explanatory,
        m._phi_internal,
        m._constant,
        m._observations,
        m._occurrence,
        m._general,
        m._profile,
        m._adam_cpp,
    )
    cov = invert_fisher_information(FI)
    # Covariances of initial states (level/trend/ARIMAState) are computed from a
    # numerical Hessian on unscaled, large-magnitude parameters; R and Python's
    # finite differences land a few-to-~15% apart there. The confidence *bounds*
    # (test_confint_matches_r) still agree to <1% because the half-widths are
    # tiny relative to those magnitudes. So the full covariance is compared
    # loosely; the smoothing-parameter block is checked tightly below.
    np.testing.assert_allclose(cov, r_vcov, rtol=0.15, atol=1e-2)

    # Smoothing-parameter covariance block (alpha/beta/gamma/phi) matches tightly.
    names = m.coef_names
    smooth_idx = [
        i
        for i, nm in enumerate(names)
        if nm == "phi" or nm[:1] in ("a", "b", "g") and not nm.startswith("ARIMA")
    ]
    if smooth_idx:
        sub = np.ix_(smooth_idx, smooth_idx)
        np.testing.assert_allclose(cov[sub], r_vcov[sub], rtol=2e-2, atol=1e-3)


@pytest.mark.parametrize("scenario", list(SCENARIOS))
def test_confint_matches_r(scenario):
    m = _fit(scenario)
    ci = m.confint(level=0.95)
    r_ci = pd.read_csv(DATA_DIR / scenario / "confint.csv", index_col=0)

    assert list(ci.index) == list(r_ci.index)

    # Confidence bounds (lower/upper) match R tightly.
    np.testing.assert_allclose(
        ci.iloc[:, 1:].to_numpy(), r_ci.iloc[:, 1:].to_numpy(), rtol=2e-2, atol=1.0
    )
    # Standard errors: looser, to absorb FD-Hessian noise on initial states.
    np.testing.assert_allclose(
        ci["S.E."].to_numpy(), r_ci["S.E."].to_numpy(), rtol=0.12, atol=1e-2
    )


def test_summary_layout_and_significance():
    m = _fit("aan")
    s = str(m.summary())
    for marker in (
        "Model estimated using",
        "Coefficients:",
        "Error standard deviation:",
        "Sample size:",
        "Number of estimated parameters:",
        "Information criteria:",
    ):
        assert marker in s
    # alpha/beta are significant for this series -> at least one star.
    assert "*" in s


def test_print_and_summary_are_separate():
    m = _fit("aan")
    concise = str(m)  # print.adam-style
    full = str(m.summary())  # summary.adam-style
    assert concise != full
    # Concise report carries the persistence-vector marker; the summary doesn't.
    assert "Persistence vector" in concise
    assert "Persistence vector" not in full
    # The summary carries the coefficient table; the concise report doesn't.
    assert "Coefficients:" in full
