"""Exact-match tests of the Python OMG class against R's ``smooth::omg()``.

Reference data is generated by
``python/tests/R scripts/generate_omg_reference.R`` into
``python/tests/data/omg/<scenario>/``. Each scenario folder contains:

* ``scalars.csv`` — loss_value, loglik, aicc, nparam
* ``fitted.csv``  — combined probability vector
* ``residuals.csv``
* ``coef.csv``    — joint B = c(modelA$B, modelB$B)
* ``forecast.csv`` — only present for h > 0 scenarios

Tolerances:
* Scalars (loss, loglik): rtol=1e-3, atol=1e-4 — tight because the
  optimised cost function value should agree closely.
* Fitted / forecast: rtol=3e-3, atol=1e-3 — slightly looser because the
  individual sub-model re-fitting after joint optimisation (backcasting)
  can converge to values with a small but systematic offset vs R.

Note: h2_seasonal_ana_mnm is skipped for scalar comparisons — Python's
NLopt finds a strictly better (lower) loss than R's optimiser for this
ANA/MNM seasonal scenario, so the R reference is a suboptimal local minimum.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

import numpy as np
import pandas as pd
import pytest

from smooth import OMG

pytestmark = pytest.mark.r_comparison

DATA_DIR = Path(__file__).parent / "data" / "omg"

RTOL = 1e-3
ATOL = 1e-4
FITTED_RTOL = 3e-3
FITTED_ATOL = 1e-3

_PYTHON_BEATS_R: set = set()


def _scenario_present(name: str) -> bool:
    return (DATA_DIR / name / "scalars.csv").exists()


def _load_scalars(name: str) -> Dict[str, float]:
    df = pd.read_csv(DATA_DIR / name / "scalars.csv")
    return {row["name"]: float(row["value"]) for _, row in df.iterrows()}


def _load_vector(name: str, kind: str) -> np.ndarray | None:
    p = DATA_DIR / name / f"{kind}.csv"
    if not p.exists():
        return None
    return pd.read_csv(p)["value"].to_numpy(dtype=float)


# --------------------------------------------------------------------------
# Fixtures
# --------------------------------------------------------------------------


@pytest.fixture(scope="module")
def y_main() -> np.ndarray:
    """Series produced by R: set.seed(41); rpois(200, 0.3)."""
    p = DATA_DIR.parent / "om" / "intermittent_demand.csv"
    return pd.read_csv(p)["y"].to_numpy(dtype=float)


@pytest.fixture(scope="module")
def y_seasonal() -> np.ndarray:
    """Series produced by R: set.seed(13); rpois(200, 0.4)."""
    p = DATA_DIR.parent / "om" / "intermittent_demand_seasonal.csv"
    return pd.read_csv(p)["y"].to_numpy(dtype=float)


@pytest.fixture(scope="module")
def data_for(y_main, y_seasonal):
    return {"main": y_main, "seasonal": y_seasonal}


# --------------------------------------------------------------------------
# Scenario registry — must match generate_omg_reference.R
# --------------------------------------------------------------------------


def _scenario(name, model_a, model_b, lags, data_key, **extra):
    base = {
        "name": name,
        "model_a": model_a,
        "model_b": model_b,
        "lags": lags,
        "data_key": data_key,
        "h": 0,
        "holdout": False,
    }
    base.update(extra)
    return base


SCENARIOS = [
    # ── Group H1: basic ETS shapes
    _scenario("h1_mnn_mnn", "MNN", "MNN", [1], "main"),
    _scenario("h1_ann_mnn", "ANN", "MNN", [1], "main"),
    _scenario("h1_ann_ann", "ANN", "ANN", [1], "main"),
    _scenario("h1_aan_mnn", "AAN", "MNN", [1], "main"),
    # ── Group H2: seasonal
    _scenario("h2_seasonal_ana_mnm", "ANA", "MNM", [1, 12], "seasonal"),
    _scenario("h2_seasonal_mnn_mnn", "MNN", "MNN", [1, 12], "seasonal"),
    # ── Group H3: holdout
    _scenario("h3_holdout_mnn", "MNN", "MNN", [1], "main", h=10, holdout=True),
    _scenario("h3_holdout_ann", "ANN", "ANN", [1], "main", h=10, holdout=True),
]


class TestOMGRComparison:
    def _fit(self, scenario: Dict[str, Any], data_for) -> OMG:
        name = scenario["name"]
        if not _scenario_present(name):
            pytest.skip(f"R reference for {name} not generated")
        y = data_for[scenario["data_key"]]
        m = OMG(
            model_a=scenario["model_a"],
            model_b=scenario["model_b"],
            lags=scenario["lags"],
            h=scenario["h"],
            holdout=scenario["holdout"],
        )
        m.fit(y)
        return m

    @pytest.mark.parametrize("scenario", SCENARIOS, ids=[s["name"] for s in SCENARIOS])
    def test_loss_value(self, scenario, data_for):
        if scenario["name"] in _PYTHON_BEATS_R:
            pytest.skip(f"{scenario['name']}: Python finds a better optimum than R")
        m = self._fit(scenario, data_for)
        scalars = _load_scalars(scenario["name"])
        np.testing.assert_allclose(
            m.loss_value,
            scalars["loss_value"],
            rtol=RTOL,
            atol=ATOL,
            err_msg=f"loss_value mismatch for {scenario['name']}",
        )

    @pytest.mark.parametrize("scenario", SCENARIOS, ids=[s["name"] for s in SCENARIOS])
    def test_loglik(self, scenario, data_for):
        if scenario["name"] in _PYTHON_BEATS_R:
            pytest.skip(f"{scenario['name']}: Python finds a better optimum than R")
        m = self._fit(scenario, data_for)
        scalars = _load_scalars(scenario["name"])
        np.testing.assert_allclose(
            m.loglik,
            scalars["loglik"],
            rtol=RTOL,
            atol=ATOL,
            err_msg=f"loglik mismatch for {scenario['name']}",
        )

    @pytest.mark.parametrize("scenario", SCENARIOS, ids=[s["name"] for s in SCENARIOS])
    def test_fitted(self, scenario, data_for):
        if scenario["name"] in _PYTHON_BEATS_R:
            pytest.skip(f"{scenario['name']}: Python finds a better optimum than R")
        m = self._fit(scenario, data_for)
        ref = _load_vector(scenario["name"], "fitted")
        np.testing.assert_allclose(
            m.fitted,
            ref,
            rtol=FITTED_RTOL,
            atol=FITTED_ATOL,
            err_msg=f"fitted mismatch for {scenario['name']}",
        )

    @pytest.mark.parametrize("scenario", SCENARIOS, ids=[s["name"] for s in SCENARIOS])
    def test_forecast(self, scenario, data_for):
        m = self._fit(scenario, data_for)
        ref = _load_vector(scenario["name"], "forecast")
        if ref is None:
            pytest.skip(f"{scenario['name']}: no forecast reference")
        fc_h = scenario["h"] if scenario["h"] > 0 else 10
        fc = (
            np.asarray(m._auto_forecast.mean.values, dtype=float)
            if m._auto_forecast is not None
            else np.asarray(m.predict(h=fc_h).mean.values, dtype=float)
        )
        np.testing.assert_allclose(
            fc,
            ref,
            rtol=FITTED_RTOL,
            atol=FITTED_ATOL,
            err_msg=f"forecast mismatch for {scenario['name']}",
        )
