"""
Comparison tests: AutoADAM Python vs R auto.adam() reference outputs.

Reference outputs were generated by:
  Rscript "tests/R scripts/auto_adam_reference.R"

Each test case checks that Python's AutoADAM selects the same:
  - Error distribution
  - ARIMA orders (AR, I, MA per lag level)
  - AICc value (within 0.05 tolerance for numerical precision)
"""

import json
from pathlib import Path

import pandas as pd

from smooth.adam_general.core.auto_adam import AutoADAM

# ---------------------------------------------------------------------------
# Load reference data
# ---------------------------------------------------------------------------

_DATA_DIR = Path(__file__).parent / "data"
_REF_FILE = _DATA_DIR / "auto_adam_reference.json"

with _REF_FILE.open() as _f:
    _REF = json.load(_f)


def _load_case(case_name):
    """Return (y, X, ref_dict) for the given case."""
    ref = _REF[case_name]
    df = pd.read_csv(_DATA_DIR / ref["data_file"])

    if case_name == "etsx":
        y = df.iloc[:, 0].values
        X = df.iloc[:, 1:].values if df.shape[1] > 1 else None
    else:
        y = df["y"].values
        X = None

    return y, X, ref


def _normalise_orders(val):
    """Normalise int/list to a comparable form."""
    if isinstance(val, int):
        return [val]
    return list(val)


# ---------------------------------------------------------------------------
# Case 1: Pure ARIMA, non-seasonal
# ---------------------------------------------------------------------------


class TestNNNNonseasonal:
    """auto.adam() with NNN model on non-seasonal data."""

    def setup_method(self):
        self.y, self.X, self.ref = _load_case("nnn_nonseasonal")
        self.m = AutoADAM(**self.ref["python_params"]).fit(self.y, self.X)

    def test_distribution(self):
        assert self.m._selected_distribution == self.ref["distribution"]

    def test_i_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["i_orders"]) == _normalise_orders(
            self.ref["i_orders"]
        )

    def test_ar_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ar_orders"]) == _normalise_orders(
            self.ref["ar_orders"]
        )

    def test_ma_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ma_orders"]) == _normalise_orders(
            self.ref["ma_orders"]
        )

    def test_aicc(self):
        assert abs(self.m.aicc - self.ref["aicc"]) < 0.05


# ---------------------------------------------------------------------------
# Case 2: Pure ARIMA, seasonal
# ---------------------------------------------------------------------------


class TestNNNSeasonal:
    """auto.adam() with NNN model on seasonal data, lags=[1,12]."""

    def setup_method(self):
        self.y, self.X, self.ref = _load_case("nnn_seasonal")
        self.m = AutoADAM(**self.ref["python_params"]).fit(self.y, self.X)

    def test_distribution(self):
        assert self.m._selected_distribution == self.ref["distribution"]

    def test_i_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["i_orders"]) == _normalise_orders(
            self.ref["i_orders"]
        )

    def test_ar_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ar_orders"]) == _normalise_orders(
            self.ref["ar_orders"]
        )

    def test_ma_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ma_orders"]) == _normalise_orders(
            self.ref["ma_orders"]
        )

    def test_aicc(self):
        assert abs(self.m.aicc - self.ref["aicc"]) < 0.05


# ---------------------------------------------------------------------------
# Case 3: ETS only (no ARIMA selection), distribution selection
# ---------------------------------------------------------------------------


class TestETSOnly:
    """auto.adam() with ZXZ, arima_select=False, distribution selection."""

    def setup_method(self):
        self.y, self.X, self.ref = _load_case("ets_only")
        self.m = AutoADAM(**self.ref["python_params"]).fit(self.y, self.X)

    def test_ets_model(self):
        assert self.ref["model_name"] in self.m.model

    def test_distribution(self):
        assert self.m._selected_distribution == self.ref["distribution"]

    def test_aicc(self):
        assert abs(self.m.aicc - self.ref["aicc"]) < 0.05


# ---------------------------------------------------------------------------
# Case 4: ETS + ARIMA selection, non-seasonal
# ---------------------------------------------------------------------------


class TestETSARIMA:
    """auto.adam() with AAN + ARIMA selection on non-seasonal data."""

    def setup_method(self):
        self.y, self.X, self.ref = _load_case("ets_arima")
        self.m = AutoADAM(**self.ref["python_params"]).fit(self.y, self.X)

    def test_ets_model(self):
        assert self.ref["model_name"] in self.m.model

    def test_distribution(self):
        assert self.m._selected_distribution == self.ref["distribution"]

    def test_ar_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ar_orders"]) == _normalise_orders(
            self.ref["ar_orders"]
        )

    def test_i_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["i_orders"]) == _normalise_orders(
            self.ref["i_orders"]
        )

    def test_ma_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ma_orders"]) == _normalise_orders(
            self.ref["ma_orders"]
        )

    def test_aicc(self):
        assert abs(self.m.aicc - self.ref["aicc"]) < 0.05


# ---------------------------------------------------------------------------
# Case 5: ETSX (ETS with external regressors)
# ---------------------------------------------------------------------------


class TestETSX:
    """auto.adam() with AAN + xreg, distribution selection."""

    def setup_method(self):
        self.y, self.X, self.ref = _load_case("etsx")
        self.m = AutoADAM(**self.ref["python_params"]).fit(self.y, self.X)

    def test_ets_model(self):
        assert self.ref["model_name"] in self.m.model

    def test_distribution(self):
        assert self.m._selected_distribution == self.ref["distribution"]

    def test_aicc(self):
        assert abs(self.m.aicc - self.ref["aicc"]) < 0.05


# ---------------------------------------------------------------------------
# Case 6: ETS + ARIMA selection, seasonal
# ---------------------------------------------------------------------------


class TestETSARIMASeasonal:
    """auto.adam() with ZXZ + ARIMA selection on seasonal data."""

    def setup_method(self):
        self.y, self.X, self.ref = _load_case("ets_arima_seasonal")
        self.m = AutoADAM(**self.ref["python_params"]).fit(self.y, self.X)

    def test_ets_model(self):
        assert self.ref["model_name"] in self.m.model

    def test_distribution(self):
        assert self.m._selected_distribution == self.ref["distribution"]

    def test_ar_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ar_orders"]) == _normalise_orders(
            self.ref["ar_orders"]
        )

    def test_i_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["i_orders"]) == _normalise_orders(
            self.ref["i_orders"]
        )

    def test_ma_orders(self):
        orders = self.m._selected_arima_orders
        assert _normalise_orders(orders["ma_orders"]) == _normalise_orders(
            self.ref["ma_orders"]
        )

    def test_aicc(self):
        assert abs(self.m.aicc - self.ref["aicc"]) < 0.05
