"""Parity tests of the Python Fisher Information against R's ``smooth::adam``.

Reference data is generated by ``python/tests/R scripts/generate_fi_reference.R``
into ``python/tests/data/fi/<scenario>/``:

* ``series.csv`` — the input series (so Python uses identical data)
* ``coef.csv``   — R's estimated coefficients (the B at which FI is taken)
* ``FI.csv``     — R's observed Fisher Information, recovered as ``solve(vcov(m))``

The decisive check evaluates the **Python FI at R's converged coefficients** and
compares it to R's FI: this isolates the FI computation from the small NLopt vs
nloptr optimiser divergence. A looser sanity check compares the FI at Python's
own optimum.

Both models are fitted with ``initial="optimal"`` so the parameter vector
contains the initial states too (richer, multi-parameter FI) and matches R's
default initialisation.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from smooth.adam_general.core.adam import ADAM
from smooth.adam_general.core.utils.var_covar import fisher_information

pytestmark = pytest.mark.r_comparison

DATA_DIR = Path(__file__).parent / "data" / "fi"

# Repo convention for R-parity numerics. The dominant FI entries match R to
# ~1e-4 relative; the tiny initial-state entries pick up O(1e-4) noise from the
# vcov round-trip used to recover R's FI.
RTOL = 1e-3
ATOL = 1e-4

SCENARIOS = [("ann", "ANN"), ("aan", "AAN")]


def _load(scenario):
    d = DATA_DIR / scenario
    y = pd.read_csv(d / "series.csv")["value"].to_numpy()
    r_B = pd.read_csv(d / "coef.csv")["value"].to_numpy()
    r_FI = pd.read_csv(d / "FI.csv").to_numpy()
    return y, r_B, r_FI


def _fi_at(m, B):
    """Python FI evaluated at ``B`` using the fitted model's internal dicts."""
    return fisher_information(
        B,
        m._model_type,
        m._components,
        m._lags_model,
        m._adam_created,
        m._persistence,
        m._initials,
        m._arima,
        m._explanatory,
        m._phi_internal,
        m._constant,
        m._observations,
        m._occurrence,
        m._general,
        m._profile,
        m._adam_cpp,
    )


@pytest.mark.parametrize("scenario,model", SCENARIOS)
def test_fi_matches_r_at_same_b(scenario, model):
    y, r_B, r_FI = _load(scenario)
    m = ADAM(model=model, lags=[1], initial="optimal", fi=True).fit(y)

    # (a) Decisive: Python FI at R's coefficients == R's FI.
    fi_at_rB = _fi_at(m, r_B)
    np.testing.assert_allclose(fi_at_rB, r_FI, rtol=RTOL, atol=ATOL)

    # FI is exposed on the fitted model and is symmetric.
    assert m.fisher_information_ is not None
    assert m.fisher_information_.shape == (len(r_B), len(r_B))
    np.testing.assert_allclose(
        m.fisher_information_, m.fisher_information_.T, rtol=0, atol=1e-8
    )


@pytest.mark.parametrize("scenario,model", SCENARIOS)
def test_fi_at_python_optimum_close_to_r(scenario, model):
    y, _, r_FI = _load(scenario)
    m = ADAM(model=model, lags=[1], initial="optimal", fi=True).fit(y)

    # (b) Sanity: FI at Python's own optimum is close to R's (looser, since the
    # two optimisers can settle at slightly different coefficient vectors).
    np.testing.assert_allclose(m.fisher_information_, r_FI, rtol=5e-2, atol=1e-2)


def test_fi_absent_by_default():
    y, _, _ = _load("ann")
    m = ADAM(model="ANN", lags=[1], initial="optimal").fit(y)
    assert m.fisher_information_ is None
