# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cesfitterwrap <- function(matvt, matF, matw, yt, vecg, Stype, seasfreq, matxt, matat, ot) {
    .Call('smooth_cesfitterwrap', PACKAGE = 'smooth', matvt, matF, matw, yt, vecg, Stype, seasfreq, matxt, matat, ot)
}

cesforecasterwrap <- function(matvt, matF, matw, h, Stype, seasfreq, matxt, matat, matFX) {
    .Call('smooth_cesforecasterwrap', PACKAGE = 'smooth', matvt, matF, matw, h, Stype, seasfreq, matxt, matat, matFX)
}

ceserrorerwrap <- function(matvt, matF, matw, yt, h, Stype, seasfreq, matxt, matat, matFX, ot) {
    .Call('smooth_ceserrorerwrap', PACKAGE = 'smooth', matvt, matF, matw, yt, h, Stype, seasfreq, matxt, matat, matFX, ot)
}

cesoptimizerwrap <- function(matvt, matF, matw, yt, vecg, h, Stype, seasfreq, multisteps, CFt, normalizer, matxt, matat, matFX, vecgX, ot) {
    .Call('smooth_cesoptimizerwrap', PACKAGE = 'smooth', matvt, matF, matw, yt, vecg, h, Stype, seasfreq, multisteps, CFt, normalizer, matxt, matat, matFX, vecgX, ot)
}

initparams <- function(Ttype, Stype, datafreq, obsR, yt, damped, phi, smoothingparameters, initialstates, seasonalcoefs) {
    .Call('smooth_initparams', PACKAGE = 'smooth', Ttype, Stype, datafreq, obsR, yt, damped, phi, smoothingparameters, initialstates, seasonalcoefs)
}

etsmatrices <- function(matvt, vecg, phi, Cvalues, ncomponentsR, modellags, Ttype, Stype, nexovars, matat, estimpersistence, estimphi, estiminit, estiminitseason, estimxreg, matFX, vecgX, gowild) {
    .Call('smooth_etsmatrices', PACKAGE = 'smooth', matvt, vecg, phi, Cvalues, ncomponentsR, modellags, Ttype, Stype, nexovars, matat, estimpersistence, estimphi, estiminit, estiminitseason, estimxreg, matFX, vecgX, gowild)
}

fitterwrap <- function(matvt, matF, matw, yt, vecg, modellags, Etype, Ttype, Stype, matxt, matat, matFX, vecgX, ot) {
    .Call('smooth_fitterwrap', PACKAGE = 'smooth', matvt, matF, matw, yt, vecg, modellags, Etype, Ttype, Stype, matxt, matat, matFX, vecgX, ot)
}

statetailwrap <- function(matvt, matF, matat, matFX, modellags, Ttype, Stype) {
    .Call('smooth_statetailwrap', PACKAGE = 'smooth', matvt, matF, matat, matFX, modellags, Ttype, Stype)
}

forecasterwrap <- function(matvt, matF, matw, h, Ttype, Stype, modellags, matxt, matat, matFX) {
    .Call('smooth_forecasterwrap', PACKAGE = 'smooth', matvt, matF, matw, h, Ttype, Stype, modellags, matxt, matat, matFX)
}

errorerwrap <- function(matvt, matF, matw, yt, h, Etype, Ttype, Stype, modellags, matxt, matat, matFX, ot) {
    .Call('smooth_errorerwrap', PACKAGE = 'smooth', matvt, matF, matw, yt, h, Etype, Ttype, Stype, modellags, matxt, matat, matFX, ot)
}

optimizerwrap <- function(matvt, matF, matw, yt, vecg, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matxt, matat, matFX, vecgX, ot) {
    .Call('smooth_optimizerwrap', PACKAGE = 'smooth', matvt, matF, matw, yt, vecg, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matxt, matat, matFX, vecgX, ot)
}

costfunc <- function(matvt, matF, matw, yt, vecg, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matxt, matat, matFX, vecgX, ot, bounds) {
    .Call('smooth_costfunc', PACKAGE = 'smooth', matvt, matF, matw, yt, vecg, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matxt, matat, matFX, vecgX, ot, bounds)
}

simulateETSwrap <- function(arrvt, materrors, matot, matF, matw, matg, Etype, Ttype, Stype, modellags) {
    .Call('smooth_simulateETSwrap', PACKAGE = 'smooth', arrvt, materrors, matot, matF, matw, matg, Etype, Ttype, Stype, modellags)
}

