# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cesfitterwrap <- function(matxt, matF, matw, yt, vecg, Stype, seasfreq, matwex, matxtreg) {
    .Call('smooth_cesfitterwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, vecg, Stype, seasfreq, matwex, matxtreg)
}

cesforecasterwrap <- function(matxt, matF, matw, h, Stype, seasfreq, matwex, matxtreg) {
    .Call('smooth_cesforecasterwrap', PACKAGE = 'smooth', matxt, matF, matw, h, Stype, seasfreq, matwex, matxtreg)
}

ceserrorerwrap <- function(matxt, matF, matw, yt, h, Stype, seasfreq, matwex, matxtreg) {
    .Call('smooth_ceserrorerwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, h, Stype, seasfreq, matwex, matxtreg)
}

cesoptimizerwrap <- function(matxt, matF, matw, yt, vecg, h, Stype, seasfreq, multisteps, CFt, normalizer, matwex, matxtreg) {
    .Call('smooth_cesoptimizerwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, vecg, h, Stype, seasfreq, multisteps, CFt, normalizer, matwex, matxtreg)
}

initparams <- function(Ttype, Stype, datafreq, obsR, yt, damped, phi, smoothingparameters, initialstates, seasonalcoefs) {
    .Call('smooth_initparams', PACKAGE = 'smooth', Ttype, Stype, datafreq, obsR, yt, damped, phi, smoothingparameters, initialstates, seasonalcoefs)
}

etsmatrices <- function(matxt, vecg1, phi, Cvalues, ncomponentsR, modellags, Ttype, Stype, nexovars, matxtreg, estimpersistence, estimphi, estiminit, estiminitseason, estimxreg) {
    .Call('smooth_etsmatrices', PACKAGE = 'smooth', matxt, vecg1, phi, Cvalues, ncomponentsR, modellags, Ttype, Stype, nexovars, matxtreg, estimpersistence, estimphi, estiminit, estiminitseason, estimxreg)
}

fitterwrap <- function(matxt, matF, matw, yt, vecg1, modellags, Etype, Ttype, Stype, matwex, matxtreg, matv, matF2, vecg2) {
    .Call('smooth_fitterwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, vecg1, modellags, Etype, Ttype, Stype, matwex, matxtreg, matv, matF2, vecg2)
}

statetailwrap <- function(matxt, matF, matxtreg, matF2, modellags, Ttype, Stype) {
    .Call('smooth_statetailwrap', PACKAGE = 'smooth', matxt, matF, matxtreg, matF2, modellags, Ttype, Stype)
}

forecasterwrap <- function(matxt, matF, matw, h, Ttype, Stype, modellags, matwex, matxtreg) {
    .Call('smooth_forecasterwrap', PACKAGE = 'smooth', matxt, matF, matw, h, Ttype, Stype, modellags, matwex, matxtreg)
}

errorerwrap <- function(matxt, matF, matw, yt, h, Etype, Ttype, Stype, modellags, matwex, matxtreg, matv, matF2, vecg2) {
    .Call('smooth_errorerwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, h, Etype, Ttype, Stype, modellags, matwex, matxtreg, matv, matF2, vecg2)
}

optimizerwrap <- function(matxt, matF, matw, yt, vecg1, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matwex, matxtreg, matv, matF2, vecg2) {
    .Call('smooth_optimizerwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, vecg1, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matwex, matxtreg, matv, matF2, vecg2)
}

costfunc <- function(matxt, matF, matw, yt, vecg1, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matwex, matxtreg, matv, matF2, vecg2, bounds, phi, Theta) {
    .Call('smooth_costfunc', PACKAGE = 'smooth', matxt, matF, matw, yt, vecg1, h, modellags, Etype, Ttype, Stype, multisteps, CFt, normalizer, matwex, matxtreg, matv, matF2, vecg2, bounds, phi, Theta)
}

simulateETSwrap <- function(matxt, errors, ot, matF, matw, vecg1, Etype, Ttype, Stype, modellags) {
    .Call('smooth_simulateETSwrap', PACKAGE = 'smooth', matxt, errors, ot, matF, matw, vecg1, Etype, Ttype, Stype, modellags)
}

ssfitterwrap <- function(matxt, matF, matw, yt, vecg1, modellags, matwex, matxtreg, matv, matF2, vecg2) {
    .Call('smooth_ssfitterwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, vecg1, modellags, matwex, matxtreg, matv, matF2, vecg2)
}

ssstatetailwrap <- function(matxt, matF, matxtreg, matF2, modellags) {
    .Call('smooth_ssstatetailwrap', PACKAGE = 'smooth', matxt, matF, matxtreg, matF2, modellags)
}

ssforecasterwrap <- function(matxt, matF, matw, h, modellags, matwex, matxtreg) {
    .Call('smooth_ssforecasterwrap', PACKAGE = 'smooth', matxt, matF, matw, h, modellags, matwex, matxtreg)
}

sserrorerwrap <- function(matxt, matF, matw, yt, h, modellags, matwex, matxtreg, matv, matF2, vecg2) {
    .Call('smooth_sserrorerwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, h, modellags, matwex, matxtreg, matv, matF2, vecg2)
}

ssoptimizerwrap <- function(matxt, matF, matw, yt, vecg1, h, modellags, multisteps, CFt, normalizer, matwex, matxtreg, matv, matF2, vecg2) {
    .Call('smooth_ssoptimizerwrap', PACKAGE = 'smooth', matxt, matF, matw, yt, vecg1, h, modellags, multisteps, CFt, normalizer, matwex, matxtreg, matv, matF2, vecg2)
}

