name: R Package UBSan Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubsan-check:
    runs-on: ubuntu-latest

    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gfortran gcc libcurl4-openssl-dev libxml2-dev libssl-dev libreadline-dev

    - name: Install R package dependencies
      run: |
        Rscript -e 'install.packages(c("remotes", "devtools", "pkgbuild", "pkgdown", "rcmdcheck"))'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Install R-devel with UBSan
      run: |
        wget https://stat.ethz.ch/R/daily/R-devel.tar.gz
        tar -xzf R-devel.tar.gz
        cd R-devel
        ./configure --enable-strict-barrier --with-ubsan --with-gcc --with-x=no
        make -j$(nproc)
        echo "R-devel installed."

    - name: Verify R-devel installation
      run: |
        cd R-devel
        ./bin/R --version
        ./bin/Rscript -e 'sessionInfo()'

    - name: Run UBSan checks
      run: |
        export PATH=$(pwd)/R-devel/bin:$PATH
        R CMD check --as-cran --use-valgrind --no-manual --no-build-vignettes .
